// <auto-generated />
using System;
using LoadoutBuilder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoadoutBuilder.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Camo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Camos");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Loadout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CotegoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CotegoryId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.WeaponCamo", b =>
                {
                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("CamoId")
                        .HasColumnType("int");

                    b.Property<int?>("LoadoutId")
                        .HasColumnType("int");

                    b.HasKey("WeaponId", "CamoId");

                    b.HasIndex("CamoId");

                    b.HasIndex("LoadoutId");

                    b.ToTable("WeaponCamos");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Weapon", b =>
                {
                    b.HasOne("LoadoutBuilder.Data.Models.Category", "Category")
                        .WithMany("Weapons")
                        .HasForeignKey("CotegoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.WeaponCamo", b =>
                {
                    b.HasOne("LoadoutBuilder.Data.Models.Camo", "Camo")
                        .WithMany("WeaponCamos")
                        .HasForeignKey("CamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoadoutBuilder.Data.Models.Loadout", null)
                        .WithMany("Weapons")
                        .HasForeignKey("LoadoutId");

                    b.HasOne("LoadoutBuilder.Data.Models.Weapon", "Weapon")
                        .WithMany("WeaponCamos")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camo");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Camo", b =>
                {
                    b.Navigation("WeaponCamos");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Category", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Loadout", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("LoadoutBuilder.Data.Models.Weapon", b =>
                {
                    b.Navigation("WeaponCamos");
                });
#pragma warning restore 612, 618
        }
    }
}
